name: ğŸšƒ Build NCurses

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 1 1-12 *"

jobs:
  raspios_lite-arm:
    name: ğŸ§ Raspberry Pi OS Lite ARM
    runs-on: ubuntu-latest
    steps:
      - name: â˜ï¸ Clone repository
        id: checkout-repository
        uses: actions/checkout@master
        with:
          repository: mirror/ncurses
          ref: refs/heads/master
      - name: ğŸ› ï¸ Build library
        id: build-library
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite:latest
          bind_mount_repository: yes
          commands: |
            ./configure \
              --prefix=/usr \
              --enable-pc-files \
              --without-cxx \
              --without-ada \
              --enable-widec \
              --with-pkg-config-libdir=/usr/lib/pkgconfig \
              --with-shared \
              --enable-sigwinch \
              --with-versioned-syms \
              --with-xterm-kbs=del \
              --enable-warnings \
              --enable-assertions \
              --disable-macros \
              --without-manpages
            make
            mv lib/libncursesw.so lib/libncursesw-arm.so
      - name: â¬†ï¸ Upload artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries-raspios_lite-arm-vt
          path: "lib/libncursesw*.so"
          if-no-files-found: error

  raspios_lite-arm64:
    name: ğŸ§ Raspberry Pi OS Lite ARM64
    runs-on: ubuntu-latest
    steps:
      - name: â˜ï¸ Clone repository
        id: checkout-repository
        uses: actions/checkout@master
        with:
          repository: mirror/ncurses
          ref: refs/heads/master
      - name: ğŸ› ï¸ Build library
        id: build-library
        uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:latest
          bind_mount_repository: yes
          commands: |
            ./configure \
              --prefix=/usr \
              --enable-pc-files \
              --without-cxx \
              --without-ada \
              --enable-widec \
              --with-pkg-config-libdir=/usr/lib/pkgconfig \
              --with-shared \
              --enable-sigwinch \
              --with-versioned-syms \
              --with-xterm-kbs=del \
              --enable-warnings \
              --enable-assertions \
              --disable-macros \
              --without-manpages
            make
            mv lib/libncursesw.so lib/libncursesw-arm64.so
      - name: â¬†ï¸ Upload artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries-raspios_lite-arm64-vt
          path: "lib/libncursesw*.so"
          if-no-files-found: error

  ubuntu-x64:
    name: ğŸ§ Ubuntu x64
    runs-on: ubuntu-latest
    steps:
      - name: â˜ï¸ Clone repository
        id: checkout-repository
        uses: actions/checkout@master
        with:
          repository: mirror/ncurses
          ref: refs/heads/master
      - name: ğŸ› ï¸ Build library
        id: build-library
        run: |
          ./configure \
             --prefix=/usr \
             --enable-pc-files \
             --without-cxx \
             --without-ada \
             --enable-widec \
             --with-pkg-config-libdir=/usr/lib/pkgconfig \
             --with-shared \
             --enable-sigwinch \
             --with-versioned-syms \
             --with-xterm-kbs=del \
             --enable-warnings \
             --enable-assertions \
             --disable-macros \
             --without-manpages
           make
           mv lib/libncursesw.so lib/libncursesw-x64.so
      - name: â¬†ï¸ Upload artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries-ubuntu-x64-vt
          path: "lib/libncursesw*.so"
          if-no-files-found: error

  macos-x64:
    name: ğŸ macOS x64
    runs-on: macOS-latest
    steps:
      - name: â˜ï¸ Clone repository
        id: checkout-repository
        uses: actions/checkout@master
        with:
          repository: mirror/ncurses
          ref: refs/heads/master
      - name: ğŸ› ï¸ Build library
        id: build-library
        run: |
          ./configure \
             --prefix=/usr \
             --enable-pc-files \
             --without-cxx \
             --without-ada \
             --enable-widec \
             --with-pkg-config-libdir=/usr/lib/pkgconfig \
             --with-shared \
             --enable-sigwinch \
             --with-versioned-syms \
             --with-xterm-kbs=del \
             --enable-warnings \
             --enable-assertions \
             --disable-macros \
             --without-manpages \
             --with-gpm=no
           make
           mv lib/libncursesw.dylib lib/libncursesw-x64.dylib
      - name: â¬†ï¸ Upload artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries-macos-x64-vt
          path: "lib/libncursesw*.dylib"
          if-no-files-found: error

  windows-x64:
    name: ğŸªŸ Windows x64
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: â˜ï¸ Clone repository
        id: checkout-repository
        uses: actions/checkout@master
        with:
          repository: mirror/ncurses
          ref: refs/heads/master

      - name: âš™ï¸ Setup environment
        id: setup-environment
        uses: msys2/setup-msys2@v2
        with:
          install: gcc make diffutils msys2-w32api-headers msys2-w32api-runtime

      - name: ğŸ› ï¸ Build library
        id: build-library
        run: |
          ./configure \
            --prefix=/mingw64 \
            --without-cxx \
            --without-ada \
            --enable-warnings \
            --enable-assertions \
            --enable-exp-win32 \
            --enable-ext-funcs \
            --disable-home-terminfo \
            --disable-echo \
            --disable-getcap \
            --disable-hard-tabs \
            --disable-leaks \
            --disable-macros \
            --disable-overwrite \
            --enable-opaque-curses \
            --enable-opaque-panel \
            --enable-opaque-menu \
            --enable-interop \
            --enable-exp-win32 \
            --enable-database \
            --with-progs \
            --without-libtool \
            --enable-pc-files \
            --with-shared \
            --with-normal \
            --without-debug \
            --enable-widec \
            --with-fallbacks=ms-terminal \
            --without-manpages
          make
          mv lib/libncursesw6.dll lib/libncursesw-x64.dll

      - name: â¬†ï¸ Upload artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries-windows-x64-vt
          path: "lib/libncursesw*.dll"
          if-no-files-found: error

  create-pr:
    name: ğŸ“ Create pull request
    runs-on: ubuntu-latest
    needs:
      [ubuntu-x64, macos-x64, windows-x64, raspios_lite-arm, raspios_lite-arm64]
    steps:
      - name: â˜ï¸ Clone repository
        id: checkout-repository
        uses: actions/checkout@v4

      - name: ğŸ“¥ Download artifacts
        id: download-artifact
        uses: actions/download-artifact@v4.1.7
        with:
          pattern: libraries*
          merge-multiple: true
          path: lib/ncurses

      - name: ğŸ“ Create pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: (chore) Update NCurses native libraries.
          committer: Alexandru Ciobanu <alex+git[bot]@ciobanu.org>
          author: Alexandru Ciobanu <alex+git[bot]@ciobanu.org>
          title: Update NCurses native library to latest master.
          body: This is an auto-generated PR with native library updates.
          delete-branch: true
          labels: dependencies
          assignees: pavkam
          branch: ncurses-lib-update
