name: ğŸ Refresh PDCurses

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 1 1-12 *"

jobs:
  windows-x64:
    name: ğŸªŸ Windows x64
    runs-on: windows-2022

    steps:
      - name: â˜ï¸ Clone repository
        id: checkout-repository
        uses: actions/checkout@master
        with:
          repository: wmcbrine/PDCurses
          ref: refs/heads/master

      - name: âš™ï¸ Setup environment
        id: setup-environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: ğŸ› ï¸ Build library
        id: build-library
        run: |
          cd wincon
          nmake WIDE=Y DLL=Y -f Makefile.vc
          ren pdcurses.dll libpdcurses-wincon-x64.dll

      - name: â¬†ï¸ Upload artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: libraries-windows-x64-wincon
          path: "wincon/*.dll"
          if-no-files-found: error

  create-pr:
    name: ğŸ“ Create pull request
    runs-on: ubuntu-latest
    needs: [windows-x64]
    steps:
      - name: â˜ï¸ Clone repository
        id: checkout-repository
        uses: actions/checkout@v4

      - name: ğŸ“¥ Download artifacts
        id: download-artifact
        uses: actions/download-artifact@v4.1.7
        with:
          pattern: libraries*
          merge-multiple: true
          path: lib/pdcurses

      - name: ğŸ“ Create pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: (chore) Update PDCurses native libraries.
          committer: Alexandru Ciobanu <alex+git[bot]@ciobanu.org>
          author: Alexandru Ciobanu <alex+git[bot]@ciobanu.org>
          title: Update PDCurses native library to latest master.
          body: This is an auto-generated PR with native library updates.
          delete-branch: true
          labels: dependencies
          assignees: pavkam
          branch: pdcurses-lib-update
