name: ğŸ“– Publish documentation

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "Sharpie/**"
      - "README.md"
      - "LICENSE"
      - "docfx.json"

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    name: ğŸ“– Generate documentation
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-github-pages.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: â˜ï¸ Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup environment
        id: setup-environment
        uses: ./.github/actions/setup

      - name: ğŸ“š Gather documentation
        id: generate-documentation
        shell: bash
        run: make generate-docs

      - name: â¬†ï¸ Upload artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./artifacts/_site

      - name: ğŸš€ Deploy to GitHub Pages
        id: deploy-to-github-pages
        uses: actions/deploy-pages@v4
